### ISSUE TITLE
Issue with CRC4 check

### ISSUE THREAD

**Issue by sken79** [millerlp/MS5803_01#2]
There is a bug in the CRC4 check code. The actual code compares the CRC4 code calculated with respect to the entire 7th coefficient, resulting, sometimes, in an erroneous "CRC code check fail".
I attached a correct MS5803_01.cpp (imho!):  lines 120. 
I also modified the function   MS_5803::MS_5803_CRC(unsigned int n_prom[]) as it referred directly to sensorCoeffs rather than to the input array n_prom, but it is mostly an "aesthetic" mod. 
Luca
[MS5803_01.cpp.zip](https://github.com/millerlp/MS5803_01/files/2768198/MS5803_01.cpp.zip)

**Comment by millerlp** [comment]
Thank you for the suggestions, they have been incorporated into the library code.
